// Prueba
export const ACTUALIZAR_PRUEBA = 'ACTUALIZAR_PRUEBA';

// Users
export const ACTUALIZAR_USERS = 'ACTUALIZAR_USERS';
export const ACTUALIZAR_SELECTED_USER = 'ACTUALIZAR_SELECTED_USER';

// Todos
export const ACTUALIZAR_TODOS = 'ACTUALIZAR_TODOS';

// Publicaciones
export const ACTUALIZAR_PUBLICACIONES = 'ACTUALIZAR_PUBLICACIONES';
